### ISSUE TITLE
Fresh install complains of a json error

### ISSUE THREAD

**Issue by davetao** [general-mobile/kotlin-android-mvvm-starter#5]
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/main.py", line 77, in cookiecutter
    extra_context=extra_context,
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 99, in generate_context
    raise ContextDecodingException(our_exc_message)
cookiecutter.exceptions.ContextDecodingException: JSON decoding error while loading "/Users/XXX/.cookiecutters/kotlin-android-mvvm-starter/cookiecutter.json".  Decoding error details: "Expecting property name: line 17 column 1 (char 559)"

I was able to fix it by removing the trailing comma in the referenced json file

**Comment by davetao** [comment]
Noticed that you have an open pull request

https://github.com/general-mobile/kotlin-android-mvvm-starter/pull/4
